export const siteConfig = {
  name: "OpticWorks Presence Lab",
  url: "https://opticworks.com",
  description:
    "Bed Presence Sensor kits for Home Assistant power users. Local mmWave hardware, statistical presence engine, and transparent tuning tools for reliable automations.",
  baseLinks: {
    home: "/",
    store: "/store",
    cart: "/store/cart",
    installGuides: "/install-guides",
    products: "/products",
    support: "/support",
    supportFaq: "/support/faq",
    supportContact: "/support/contact",
    supportWarranty: "/support/warranty",
    supportOops: "/support/oops",
    supportLegal: "/support/legal",
    supportTintingLaws: "/support/legal/tinting-laws",
    supportPrivacy: "/support/legal/privacy",
    supportTerms: "/support/legal/terms",
    supportOrders: "/support/orders",
    supportBilling: "/support/billing",
    supportCompatibility: "/support/compatibility",
  },
}
