export const siteConfig = {
  name: "OpticWorks Window Tinting",
  url: "https://opticworks.com",
  description: "Professional-grade DIY window tinting kits and installation solutions. Transform your vehicle with precision-cut ceramic films and foolproof installation tools.",
  baseLinks: {
    home: "/",
    store: "/store",
    cart: "/store/cart",
    installGuides: "/install-guides",
    products: "/products",
    support: "/support",
    supportFaq: "/support/faq",
    supportContact: "/support/contact",
    supportWarranty: "/support/warranty",
    supportOops: "/support/oops",
    supportLegal: "/support/legal",
    supportTintingLaws: "/support/legal/tinting-laws",
    supportPrivacy: "/support/legal/privacy",
    supportTerms: "/support/legal/terms",
  },
}
